/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'action' : string,
  'user' : Principal,
  'timestamp' : Time,
}
export type BudgetRange = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface FileReference { 'hash' : string, 'path' : string }
export interface Note {
  'content' : string,
  'author' : Principal,
  'placeId' : string,
  'timestamp' : Time,
}
export interface Place {
  'id' : string,
  'status' : Array<PlaceStatus>,
  'country' : string,
  'quickFacts' : QuickFacts,
  'city' : string,
  'tags' : Array<string>,
  'bestTimeToVisit' : string,
  'attractions' : Array<string>,
  'author' : Principal,
  'stateRegion' : string,
  'notes' : string,
  'timestamp' : Time,
  'budgetRange' : BudgetRange,
  'images' : Array<string>,
}
export type PlaceStatus = { 'wouldReturn' : null } |
  { 'wantToGo' : null } |
  { 'researched' : null } |
  { 'visited' : null } |
  { 'toResearch' : null } |
  { 'planning' : null };
export interface QuickFacts {
  'bestKnownFor' : string,
  'hiddenGem' : string,
  'localTip' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addNote' : ActorMethod<[Note], undefined>,
  'addPlace' : ActorMethod<[Place], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autocomplete' : ActorMethod<[string], string>,
  'deleteAllPlaces' : ActorMethod<[], undefined>,
  'deletePlace' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'filterPlacesByCountry' : ActorMethod<[string], Array<Place>>,
  'findPlaceFromText' : ActorMethod<[string], string>,
  'forgotPassword' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getActivityLog' : ActorMethod<[], Array<ActivityEntry>>,
  'getAllPlaces' : ActorMethod<[], Array<Place>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getLandingPageVideo' : ActorMethod<
    [],
    [] | [{ 'posterPath' : [] | [string], 'videoPath' : string }]
  >,
  'getNotesForPlace' : ActorMethod<[string], Array<Note>>,
  'getPlace' : ActorMethod<[string], [] | [Place]>,
  'getPlaceDetails' : ActorMethod<[string], string>,
  'getRandomToResearchPlace' : ActorMethod<[], [] | [Place]>,
  'getStats' : ActorMethod<
    [],
    {
      'researchedPlaces' : bigint,
      'toResearchPlaces' : bigint,
      'totalPlaces' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'logUserSignup' : ActorMethod<[], undefined>,
  'loginUser' : ActorMethod<
    [string, string],
    {
        'ok' : {
          'displayName' : string,
          'sessionToken' : string,
          'isAdmin' : boolean,
        }
      } |
      { 'err' : string }
  >,
  'logoutUser' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'nearbySearch' : ActorMethod<[number, number], string>,
  'queryAutocomplete' : ActorMethod<[string], string>,
  'register' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'resetPassword' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPlaces' : ActorMethod<[string], Array<Place>>,
  'setLandingPageVideo' : ActorMethod<[string, [] | [string]], undefined>,
  'textSearch' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePlace' : ActorMethod<[Place], undefined>,
  'validateSession' : ActorMethod<
    [string],
    {
        'ok' : {
          'username' : string,
          'displayName' : string,
          'isAdmin' : boolean,
        }
      } |
      { 'err' : string }
  >,
  'verifyEmail' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];