/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuickFacts {
    bestKnownFor: string;
    hiddenGem: string;
    localTip: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Place {
    id: string;
    status: Array<PlaceStatus>;
    country: string;
    quickFacts: QuickFacts;
    city: string;
    tags: Array<string>;
    bestTimeToVisit: string;
    attractions: Array<string>;
    author: Principal;
    stateRegion: string;
    notes: string;
    timestamp: Time;
    budgetRange: BudgetRange;
    images: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface ActivityEntry {
    action: string;
    user: Principal;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export interface Note {
    content: string;
    author: Principal;
    placeId: string;
    timestamp: Time;
}
export enum BudgetRange {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum PlaceStatus {
    wouldReturn = "wouldReturn",
    wantToGo = "wantToGo",
    researched = "researched",
    visited = "visited",
    toResearch = "toResearch",
    planning = "planning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addNote(note: Note): Promise<void>;
    addPlace(place: Place): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    autocomplete(input: string): Promise<string>;
    deleteAllPlaces(): Promise<void>;
    deletePlace(id: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    filterPlacesByCountry(country: string): Promise<Array<Place>>;
    findPlaceFromText(input: string): Promise<string>;
    forgotPassword(email: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getActivityLog(): Promise<Array<ActivityEntry>>;
    getAllPlaces(): Promise<Array<Place>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFileReference(path: string): Promise<FileReference>;
    getLandingPageVideo(): Promise<{
        posterPath?: string;
        videoPath: string;
    } | null>;
    getNotesForPlace(placeId: string): Promise<Array<Note>>;
    getPlace(id: string): Promise<Place | null>;
    getPlaceDetails(placeId: string): Promise<string>;
    getRandomToResearchPlace(): Promise<Place | null>;
    getStats(): Promise<{
        researchedPlaces: bigint;
        toResearchPlaces: bigint;
        totalPlaces: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    logUserSignup(): Promise<void>;
    loginUser(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            displayName: string;
            sessionToken: string;
            isAdmin: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    logoutUser(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    nearbySearch(lat: number, lon: number): Promise<string>;
    queryAutocomplete(input: string): Promise<string>;
    register(username: string, password: string, email: string, displayName: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerFileReference(path: string, hash: string): Promise<void>;
    resetPassword(token: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPlaces(term: string): Promise<Array<Place>>;
    setLandingPageVideo(videoPath: string, posterPath: string | null): Promise<void>;
    textSearch(searchQuery: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePlace(place: Place): Promise<void>;
    validateSession(sessionToken: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            displayName: string;
            isAdmin: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifyEmail(token: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { BudgetRange as _BudgetRange, Place as _Place, PlaceStatus as _PlaceStatus, QuickFacts as _QuickFacts, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addNote(arg0: Note): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0);
            return result;
        }
    }
    async addPlace(arg0: Place): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlace(to_candid_Place_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlace(to_candid_Place_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autocomplete(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.autocomplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autocomplete(arg0);
            return result;
        }
    }
    async deleteAllPlaces(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllPlaces();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllPlaces();
            return result;
        }
    }
    async deletePlace(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlace(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async filterPlacesByCountry(arg0: string): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPlacesByCountry(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPlacesByCountry(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async findPlaceFromText(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.findPlaceFromText(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findPlaceFromText(arg0);
            return result;
        }
    }
    async forgotPassword(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.forgotPassword(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forgotPassword(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLog(): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return result;
        }
    }
    async getAllPlaces(): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlaces();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlaces();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getLandingPageVideo(): Promise<{
        posterPath?: string;
        videoPath: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandingPageVideo();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandingPageVideo();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesForPlace(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesForPlace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesForPlace(arg0);
            return result;
        }
    }
    async getPlace(arg0: string): Promise<Place | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlace(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlace(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaceDetails(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaceDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaceDetails(arg0);
            return result;
        }
    }
    async getRandomToResearchPlace(): Promise<Place | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomToResearchPlace();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomToResearchPlace();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<{
        researchedPlaces: bigint;
        toResearchPlaces: bigint;
        totalPlaces: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async logUserSignup(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserSignup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserSignup();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            displayName: string;
            sessionToken: string;
            isAdmin: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutUser(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async nearbySearch(arg0: number, arg1: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.nearbySearch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nearbySearch(arg0, arg1);
            return result;
        }
    }
    async queryAutocomplete(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAutocomplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAutocomplete(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchPlaces(arg0: string): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlaces(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlaces(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setLandingPageVideo(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLandingPageVideo(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLandingPageVideo(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async textSearch(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.textSearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.textSearch(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePlace(arg0: Place): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlace(to_candid_Place_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlace(to_candid_Place_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateSession(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            username: string;
            displayName: string;
            isAdmin: boolean;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmail(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmail(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmail(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BudgetRange_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetRange): BudgetRange {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PlaceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceStatus): PlaceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Place_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Place): Place {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        posterPath: [] | [string];
        videoPath: string;
    }]): {
    posterPath?: string;
    videoPath: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Place]): Place | null {
    return value.length === 0 ? null : from_candid_Place_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Array<_PlaceStatus>;
    country: string;
    quickFacts: _QuickFacts;
    city: string;
    tags: Array<string>;
    bestTimeToVisit: string;
    attractions: Array<string>;
    author: Principal;
    stateRegion: string;
    notes: string;
    timestamp: _Time;
    budgetRange: _BudgetRange;
    images: Array<string>;
}): {
    id: string;
    status: Array<PlaceStatus>;
    country: string;
    quickFacts: QuickFacts;
    city: string;
    tags: Array<string>;
    bestTimeToVisit: string;
    attractions: Array<string>;
    author: Principal;
    stateRegion: string;
    notes: string;
    timestamp: Time;
    budgetRange: BudgetRange;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_vec_n13(_uploadFile, _downloadFile, value.status),
        country: value.country,
        quickFacts: value.quickFacts,
        city: value.city,
        tags: value.tags,
        bestTimeToVisit: value.bestTimeToVisit,
        attractions: value.attractions,
        author: value.author,
        stateRegion: value.stateRegion,
        notes: value.notes,
        timestamp: value.timestamp,
        budgetRange: from_candid_BudgetRange_n16(_uploadFile, _downloadFile, value.budgetRange),
        images: value.images
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    posterPath: [] | [string];
    videoPath: string;
}): {
    posterPath?: string;
    videoPath: string;
} {
    return {
        posterPath: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.posterPath)),
        videoPath: value.videoPath
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wouldReturn: null;
} | {
    wantToGo: null;
} | {
    researched: null;
} | {
    visited: null;
} | {
    toResearch: null;
} | {
    planning: null;
}): PlaceStatus {
    return "wouldReturn" in value ? PlaceStatus.wouldReturn : "wantToGo" in value ? PlaceStatus.wantToGo : "researched" in value ? PlaceStatus.researched : "visited" in value ? PlaceStatus.visited : "toResearch" in value ? PlaceStatus.toResearch : "planning" in value ? PlaceStatus.planning : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): BudgetRange {
    return "low" in value ? BudgetRange.low : "high" in value ? BudgetRange.high : "medium" in value ? BudgetRange.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        displayName: string;
        sessionToken: string;
        isAdmin: boolean;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        displayName: string;
        sessionToken: string;
        isAdmin: boolean;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        username: string;
        displayName: string;
        isAdmin: boolean;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        username: string;
        displayName: string;
        isAdmin: boolean;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Place>): Array<Place> {
    return value.map((x)=>from_candid_Place_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlaceStatus>): Array<PlaceStatus> {
    return value.map((x)=>from_candid_PlaceStatus_n14(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetRange_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): _BudgetRange {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceStatus): _PlaceStatus {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Place_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Place): _Place {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Array<PlaceStatus>;
    country: string;
    quickFacts: QuickFacts;
    city: string;
    tags: Array<string>;
    bestTimeToVisit: string;
    attractions: Array<string>;
    author: Principal;
    stateRegion: string;
    notes: string;
    timestamp: Time;
    budgetRange: BudgetRange;
    images: Array<string>;
}): {
    id: string;
    status: Array<_PlaceStatus>;
    country: string;
    quickFacts: _QuickFacts;
    city: string;
    tags: Array<string>;
    bestTimeToVisit: string;
    attractions: Array<string>;
    author: Principal;
    stateRegion: string;
    notes: string;
    timestamp: _Time;
    budgetRange: _BudgetRange;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_vec_n3(_uploadFile, _downloadFile, value.status),
        country: value.country,
        quickFacts: value.quickFacts,
        city: value.city,
        tags: value.tags,
        bestTimeToVisit: value.bestTimeToVisit,
        attractions: value.attractions,
        author: value.author,
        stateRegion: value.stateRegion,
        notes: value.notes,
        timestamp: value.timestamp,
        budgetRange: to_candid_BudgetRange_n6(_uploadFile, _downloadFile, value.budgetRange),
        images: value.images
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceStatus): {
    wouldReturn: null;
} | {
    wantToGo: null;
} | {
    researched: null;
} | {
    visited: null;
} | {
    toResearch: null;
} | {
    planning: null;
} {
    return value == PlaceStatus.wouldReturn ? {
        wouldReturn: null
    } : value == PlaceStatus.wantToGo ? {
        wantToGo: null
    } : value == PlaceStatus.researched ? {
        researched: null
    } : value == PlaceStatus.visited ? {
        visited: null
    } : value == PlaceStatus.toResearch ? {
        toResearch: null
    } : value == PlaceStatus.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetRange): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == BudgetRange.low ? {
        low: null
    } : value == BudgetRange.high ? {
        high: null
    } : value == BudgetRange.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PlaceStatus>): Array<_PlaceStatus> {
    return value.map((x)=>to_candid_PlaceStatus_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
